-- Rich Signal - Supabase 스키마
-- Supabase 대시보드 > SQL Editor에서 실행

-- AI 리포트 캐시
CREATE TABLE IF NOT EXISTS ai_reports (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date TEXT NOT NULL,
  report      JSONB NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ai_reports_date ON ai_reports (report_date, created_at DESC);

-- 긴급 알림 이력
CREATE TABLE IF NOT EXISTS alert_history (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_level     TEXT NOT NULL,
  kospi_chg       NUMERIC(6,2),
  kosdaq_chg      NUMERIC(6,2),
  causes          JSONB,
  immediate_action TEXT,
  watch_for       TEXT,
  triggered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE ai_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_only" ON ai_reports FOR ALL USING (auth.role() = 'service_role');

ALTER TABLE alert_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_write" ON alert_history FOR INSERT USING (auth.role() = 'service_role');
CREATE POLICY "auth_read" ON alert_history FOR SELECT USING (auth.role() IN ('service_role','authenticated'));
